added answer schema
hack4impact-upenn/asap-f22 pull request #1
Opened 2022-10-09 19:58 UTC by annabay04

2022-10-11 02:35 UTC, rosewang01 requested changes
Can you change the ID type to be some kind of numerical type? Finally, can we change the required fields to be true? I think the resources will be a question type.

2022-10-11 13:53 UTC, rosewang01 requested changes
Just one small change! Sorry about that :)

2022-10-11 13:53 UTC, rosewang01 commented on server/src/models/answer.ts
> +  _id: number;
could we change this from number to int?

2022-10-11 13:54 UTC, rosewang01 approved these changes

2022-10-15 15:31 UTC, vszammit approved these changes

2022-10-18 22:29 UTC, rosewang01 approved these changes

2022-10-18 22:29 UTC, merged